/**
 * STORM — weather, on the beat.
 *
 * Two cloud decks crossing overhead, rain in two planes, and a strike on the
 * downbeats that land hardest. The bolt is generated by midpoint displacement
 * from an rng seeded with the frame index of the strike itself, so it is a
 * different bolt every time and the same bolt on every render.
 */
import { blobSheet, boltPath, particles, scroll, strokeBolt } from "../fields.js";
import { css } from "../palette.js";
import { decay } from "../signals.js";

export const id = "storm";
export const name = "Storm";

/** Frames a strike stays lit. */
const STRIKE_LIFE = 9;

export function init(a) {
  const r = a.rng(6151);
  const g = a.palette.ground;
  const deck = [Math.round(g[0] * 1.5 + 12), Math.round(g[1] * 1.5 + 13), Math.round(g[2] * 1.6 + 18)].join(",");
  const lit = a.palette.bone.map((v) => Math.round(v * 0.4 + 10)).join(",");

  a.stormHigh = blobSheet(Math.round(a.W * 0.8), Math.round(a.H * 0.55), r, {
    count: 60,
    radius: [0.12, 0.44],
    colours: [`rgba(${deck},1)`, `rgba(${lit},1)`],
    alpha: [0.08, 0.26],
    squash: 0.5,
  });
  a.stormLow = blobSheet(Math.round(a.W * 0.55), Math.round(a.H * 0.4), r, {
    count: 44,
    radius: [0.10, 0.34],
    colours: [`rgba(${deck},1)`],
    alpha: [0.06, 0.20],
    squash: 0.55,
  });
  a.stormRainFar = particles(r, 130, { speed: [0.010, 0.020], size: [0.5, 1.2], dim: [0.06, 0.20] });
  a.stormRainNear = particles(r, 60, { speed: [0.022, 0.040], size: [1.0, 2.2], dim: [0.14, 0.40] });
}

export function draw(ctx, s, a) {
  const { W, H, palette } = a;
  const g = palette.ground;
  const bone = css(palette.bone);

  ctx.fillStyle = css([g[0] * 0.62 + 4, g[1] * 0.64 + 5, g[2] * 0.86 + 9]);
  ctx.fillRect(0, 0, W, H);

  scroll(ctx, a.stormHigh, -s.i * 0.6, Math.sin(s.i * 0.0016) * H * 0.01 - H * 0.06, W * 0.8, H * 0.55);
  ctx.globalAlpha = 0.8;
  scroll(ctx, a.stormLow, s.i * 1.1, Math.sin(s.i * 0.0027 + 2) * H * 0.012, W * 0.55, H * 0.4);
  ctx.globalAlpha = 1;

  // --- rain, two planes ----------------------------------------------------
  ctx.strokeStyle = bone;
  ctx.lineWidth = Math.max(1, W * 0.0008);
  for (const [set, slant, len] of [[a.stormRainFar, 0.10, 0.035], [a.stormRainNear, 0.14, 0.06]]) {
    ctx.beginPath();
    for (const p of set) {
      const y = (((p.y + s.i * p.speed) % 1) + 1) % 1;
      const x = ((p.x - y * slant) % 1 + 1) % 1;
      ctx.globalAlpha = p.dim;
      ctx.moveTo(x * W, y * H);
      ctx.lineTo(x * W - slant * W * 0.12, y * H + len * H);
    }
    ctx.stroke();
  }
  ctx.globalAlpha = 1;

  // --- the strike ----------------------------------------------------------
  const live = decay(s.sinceDownbeat, STRIKE_LIFE);
  const force = live * Math.max(0, s.kick - 0.35) / 0.65;
  if (force > 0.02) {
    const at = Math.round(s.i - (s.sinceDownbeat > 1e8 ? 0 : s.sinceDownbeat));
    const r = a.rng(9013 + at * 131);
    const x0 = W * (0.15 + r() * 0.7);
    const pts = boltPath(r, x0, -H * 0.05, x0 + (r() - 0.5) * W * 0.3, H * (0.55 + r() * 0.45), W * 0.10, 5);

    // the whole sky lifts first, then the bolt is drawn over it
    ctx.globalCompositeOperation = "lighter";
    ctx.globalAlpha = force * 0.16;
    ctx.fillStyle = bone;
    ctx.fillRect(0, 0, W, H);
    ctx.globalAlpha = Math.min(1, force * 1.2);
    strokeBolt(
      ctx, pts,
      `rgba(${palette.bone.map(Math.round).join(",")},0.22)`,
      "#ffffff",
      Math.max(1, W * 0.0016),
    );
    if (r() > 0.4) {
      const fork = Math.floor(pts.length * (0.4 + r() * 0.4));
      const [fx, fy] = pts[fork];
      strokeBolt(
        ctx,
        boltPath(r, fx, fy, fx + (r() - 0.5) * W * 0.25, fy + H * 0.25, W * 0.05, 4),
        `rgba(${palette.ember.map(Math.round).join(",")},0.20)`,
        "#ffffff",
        Math.max(1, W * 0.0010),
      );
    }
    ctx.globalAlpha = 1;
    ctx.globalCompositeOperation = "source-over";
  }
}
